[package]
name = "rustawssdk"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1"
tokio = { version = "1", features = ["full"] }
aws-sdk-dynamodb = "1"
aws-sdk-ecs = "1"
aws-sdk-ecr = "1"
aws-sdk-batch = "1"
aws-sdk-ec2 = "1"
aws-sdk-iam = "1"
aws-sdk-organizations = "1"
aws-sdk-ssoadmin = "1"
aws-sdk-identitystore = "1"
async-recursion = "1"
futures = "0.3"
